services:
  livekit-bridge:
    build: .
    network_mode: "host"
    environment:
      # These should be set in a .env file or passed as environment variables
      LIVEKIT_HOST: ${LIVEKIT_HOST}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      IDENTITY: ${IDENTITY:-microcontroller-bridge}
    restart: unless-stopped
